#!/bin/sh

# Copyright (c) 2023 Eliah Kagan
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

set -eu

nl() {
    printf '\n' >&2
}

msg() {
    printf '%s: %s\n' "$0" "$1" >&2
}

nl
msg 'Customizing global git configuration...'
git config --global color.diff.new blue
msg '...global git configuration customized.'

nl
msg 'Customizing fish (the friendly interactive shell)...'
sudo chsh -s /usr/bin/fish "$USER"
fish -c 'set -U __fish_git_prompt_color_cleanstate brgreen'
fish -c 'set -U __fish_git_prompt_show_informative_status true'
fish -c 'set -U __fish_git_prompt_showcolorhints true'
fish -c 'set -U __fish_git_prompt_showuntrackedfiles true'
fish -c 'set -U __fish_git_prompt_showupstream verbose'
msg '...fish customized.'
